### PR TITLE
copy gitattributes file with fresh project

### PR DESCRIPTION
**Pull request by GantMan**
I agree this is probably smartest move until upstream has a change.

### CODE REVIEW

**Review by skellock — CHANGES_REQUESTED** [review]
This will overwrite the file that comes with React Native.  Lets append.

**Comment by GantMan** [comment]
good catch, I didn't notice that they had one.  Still working on playing catchup it seems.

**Comment by skellock** [comment]
I learned about this yesterday.  I honestly never knew what .gitattributes did.

**Comment by GantMan** [comment]
Ok, I updated the code to _append_ to git attributes.  Which is awesome.

Tested it and it works:
` $ ignite n SafeTest5 --boilerplate /Users/gantman/Documents/Projects/rn/ignite-ir-boilerplate-2016`
Success!

What you said got me thinking.  And it looks like we overwrite the editorconfig that comes from RN.  So, in a small commit, I updated the editor config to be a merge of theirs and ours.   I know the proper fix is far from that, but this at least temporarily fixes something that was "broken".

Fortunately these files aren't modified often, and when they are the effect isn't drastic.

**Review by skellock — APPROVED** [review]

**Pull request merged**
